name: abflow
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - python=3.12
  - pip
  - biopython=1.84
  - pandas=2.2.2
  - numpy=1.26.4
  - pytorch>=2.4
  - lightning==2.2.1
  - wandb=0.18.5
  - matplotlib
  - seaborn
  - ipykernel
  - jupyter
  - notebook
  - abnumber
  - pdbfixer
  - einops
  - pip:
      - lmdb
      - texttable
      - easydict