---

# wandb settings
project_name: flow_matching
model_name: abflow

# shared settings
shared:
    design_mode: &design_mode ["sequence", "backbone"] # Options: ["sequence", "backbone", "sidechain"]
    seed: &seed 2030
    confidence: &confidence False
    dataset2use: &dataset2use sabdab
    binder_loss: &binder_loss False

# training settings
trainer:
    devices: 8
    max_epochs: 200
    precision: 32-true
    gradient_clip_val: 1.0
    val_check_interval: 1.0
    accumulate_grad_batches: 4
    log_every_n_steps: 100
checkpoint:
    ignore_mismatched_state_dict: False
    path: null
    ema_path: null 
    load_optimizer: False

# abflow datamodule settings
datamodule:
    num_workers: 12
    batch_size: 1
    redesign:
        framework: False
        hcdr1: True
        hcdr2: True
        hcdr3: True
        lcdr1: True
        lcdr2: True
        lcdr3: True
    max_crop_size: 356
    antigen_crop_size: 100
    random_sample_sizes: False
    dataset:
        name: *dataset2use # oas_sabdab
        seed: *seed
        num_val_cluster: 10
        paths:
            data: /scratch/hz362/datavol/data 
            model: /scratch/hz362/datavol/model
    binder_loss: *binder_loss

# abflow model settings
model:
    loss_weighting:
        sequence_vf_loss: 100.0
        translation_vf_loss: 1.0
        rotation_vf_loss: 10.0
        dihedral_vf_loss: 10.0
        distogram_loss: 2.0
        binder_loss: 1.0
        entropy_loss: 1.0
        confidence_lddt_loss: 1
        confidence_de_loss: 1
        confidence_ae_loss: 1
        clash_loss: 0.1
        bond_angle_loss: 0.1
        bond_length_loss: 0.1
    learning_rate: 0.0001
    loss_combination_method: mvdr # static, mvdr
    design_mode: *design_mode
    seed: *seed
    confidence: *confidence
    dataset_name: *dataset2use
    binder_loss: *binder_loss

# abflow network settings
network:
    is_training: True
    design_mode: *design_mode
    confidence: *confidence
    binder_loss: *binder_loss
    c_s: 512 # default: 384
    c_z: 128 # default: 128
    n_condition_module_blocks: 2 # default: 48
    n_denoising_module_blocks: 4 # default: 24
    n_confidence_module_blocks: 1 # default: 4
    n_cycle: 4
    denoising_cycle: 1
    mini_rollout_steps: 20
    full_rollout_steps: 100
    label_smoothing: 0.0
    max_time_clamp: 0.99
    network_params:
        Pairformer:
            dropout_rowwise_probabilty: 0.2
            dropout_columnwise_probabilty: 0.2
            TriangleAttentionStartingNode:
                n_head: 6
            TriangleAttentionEndingNode:
                n_head: 6
            AttentionPairBias:
                n_head: 6
        InvariantPointAttention:
            dropout_probability: 0.2
            n_head: 6
            n_query_points: 8
            n_point_values: 16